### ISSUE TITLE
Consider updating from `elf` to `object` library

### ISSUE THREAD

**Issue by ppannuto** [tock/elf2tab#34]
The [`elf`](https://github.com/cole14/rust-elf/) package that this is built on hasn't been touched in almost 5 years. It looks like the Rust ecosystem has settled on the [`object`](https://crates.io/crates/object) package for manipulating object files of all forms.

Not a priority, as the code we have works, and elf files aren't changing anytime soon, but this is some brittleness we're exposed to; doing anything fancier with elfs is probably better served with the new library.

**Comment by bradjc** [comment]
It may very well be that the poorly named library called "object" is better, but the lack of examples have worn out my patience for trying to use it. In trying to support every file they have seemingly made trying to parse an elf overly difficult.
