### ISSUE TITLE
Padding between sections only < 100

### ISSUE THREAD

**Issue by bincsh** [tock/elf2tab#54]
Padding is important to maintain the correct addresses when PIC is not in place. Currently, elf2tab only pads up to 99 bytes. It must pad between sections always, and **to panic if it doesn't** (maybe warning, if section is not .text).

Found it when building an app using a library that has .rodata aligned to 1024 bytes. This section (.rodata) gets linked in .text for Tock Apps. I've fixed this problem by increasing the number to 4096 bytes.

**Comment by hudson-ayers** [comment]
Fixed by https://github.com/tock/elf2tab/pull/55
