### ISSUE TITLE
Generating a large amount of padding?

### ISSUE THREAD

**Issue by stevefan1999-personal** [tock/elf2tab#80]
I'm using ESP32 as a target, I noticed the binary I generated indeed didn't fit. I started out in  https://github.com/tock/tock/discussions/3614, but then I quickly realized it is the binary.hex problem. The padding comes from elf2tab here...I have no idea why

**Comment by bradjc** [comment]
Can you run `readelf -lS` on the input elf and post the output?

**Comment by stevefan1999-personal** [comment]
@bradjc Yes I confirmed it is generating for wrong target...
