### ISSUE TITLE
convert.rs: excess padding due to section being in ram

### ISSUE THREAD

**Issue by twilfredo** [tock/elf2tab#83]
I'm running into an issue with elf2tab when compiling a libtock-rs app that is linked with multiple larger external libraries. In that, I am seeing the "Warning! Inserting a large amount of padding" warning and the generated tab is ~512MB. This is all padding and the actual binary is ~20Kb.

The elf has the following program headers:

```
Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x001080 0x00040080 0x00040080 0x02e30 0x02e30 R E 0x1000
  LOAD           0x003eb0 0x00042eb0 0x00042eb0 0x00e19 0x00e19 R   0x1000
  LOAD           0x005000 0x20008000 0x00043cc9 0x00100 0x0025c RW  0x1000
  LOAD           0x00525c 0x2000825c 0x2000825c 0x010dc 0x010dc RW  0x1000
  GNU_RELRO      0x0062c8 0x200092c8 0x200092c8 0x00070 0x00d38 R   0x1
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0
```
The padding occurs on `LOAD           0x00525c 0x2000825c 0x2000825c 0x010dc 0x010dc RW  0x1000` and the last valid section that goes into flash.

I'm compiling for the `nrf52840` and have a work-around fix for this,

```
diff --git a/src/convert.rs b/src/convert.rs
index a94c09f..5786bcc 100644
--- a/src/convert.rs
+++ b/src/convert.rs
@@ -642,6 +642,15 @@ pub fn elf_to_tbf(
             }
         }
 
+        // Check that the segment lies in flash.
+        if let Some(sram_addr) = fixed_address_ram {
+            if segment.p_paddr >= sram_addr as u64 {
+                continue;
+            }
+        }
+
+        println!("segment_type: {:?} -> {:x}", segment.p_type, segment.p_paddr);
+
         // It's possible the linker started this segment _before_ the start of
         // the flash region. We edit the segment to remove the portion that
         // starts before the start of flash.
```

With this change I can generate a loadable binary ~20Kb. Although I don't think it's an appropriate fix (i.e the address layout maybe different etc...)?

What are your thoughts on such a segment... it seems like it's to reserve RAM, but `v_addr == p_addr` situation is odd? and how best to address it?

**Comment by bradjc** [comment]
Why is the linker trying to place a load-ed section into address 0x2000825c? This seems like an issue with the linker script.

We're trying to ensure that elf2tab isn't doing any heuristics with elf files and is instead parsing them as intended. Given that, I'm not inclined to add a check of this sort. However, if we can convince ourselves that this is a linker bug then it would be more reasonable for elf2tab to work around the issue.

**Comment by twilfredo** [comment]
Closing this, it turned out to be an issue with the linker script as @bradjc mentioned :)
